# Generated by Django 2.0.2 on 2019-05-21 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartelera', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obra',
            options={'ordering': ['created'], 'verbose_name': 'Obra', 'verbose_name_plural': 'Títulos y Autores'},
        ),
    ]
