# Generated by Django 2.0.2 on 2019-02-28 18:43

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biblioteca', '0002_etiquetasbiblio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('autor', models.CharField(max_length=200, null=True, verbose_name='Autor')),
                ('descripcion', ckeditor.fields.RichTextField(max_length=18000, verbose_name='Escribe aquí una breve descripción del libro')),
                ('imagen', models.ImageField(upload_to='nodos', verbose_name='portada del libro')),
                ('isbn', models.FloatField(blank=True, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, null=True, verbose_name='Introduce el ISBN')),
                ('editorial', models.CharField(max_length=200, null=True, verbose_name='Editorial')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Año de edición')),
                ('pais', models.CharField(default='México', max_length=20, verbose_name='País y/o Edo')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('cate_estudio', models.ManyToManyField(help_text='Seleccione las categorías de estudio que contine el libro.', related_name='get_cat_estudy', to='biblioteca.CategoryStudyBiblio', verbose_name='Categorías de estudio')),
                ('categorias', models.ManyToManyField(related_name='get_nodos', to='biblioteca.etiquetasBiblio', verbose_name='Etiquetas')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['created'],
            },
        ),
    ]
