# Generated by Django 2.0.2 on 2019-02-28 19:51

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('info', ckeditor.fields.RichTextField(max_length=8000, verbose_name='Información')),
                ('imagenPerfil', models.ImageField(upload_to='nodos', verbose_name='Imagen de perfil')),
                ('imagenExtra', models.ImageField(upload_to='nodos', verbose_name='Imágen extra')),
                ('linkface', models.URLField(blank=True, null=True, verbose_name='link')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'Compañía',
                'verbose_name_plural': 'Compañía',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='propuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propuesta', ckeditor.fields.RichTextField(max_length=18000, verbose_name='Propuesta del Grupo')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'Propuesta del Grupo',
                'verbose_name_plural': 'Propuesta del Grupo',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='repertorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('autor', models.CharField(max_length=200, null=True, verbose_name='Autor')),
                ('descripcion', ckeditor.fields.RichTextField(max_length=18000, verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='grupo', verbose_name='Imagen')),
                ('editorial', models.CharField(max_length=200, null=True, verbose_name='Editorial')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Repertorio',
                'verbose_name_plural': 'Repertorio',
                'ordering': ['created'],
            },
        ),
    ]
