# Generated by Django 2.0.2 on 2019-02-28 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repertorio',
            name='editorial',
        ),
    ]
