# Generated by Django 2.0.2 on 2019-03-08 04:07

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorias', models.CharField(max_length=200, verbose_name='Categoria')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria de etiqueta blog',
                'verbose_name_plural': 'Categorias del Blog',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='CategoryStudyBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=200, verbose_name='Categoria')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria de estudio del blog',
                'verbose_name_plural': 'Categorias de estudio del Blog',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='entradaBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('imagen', models.ImageField(upload_to='blog', verbose_name='Imagen principal')),
                ('categoria', models.CharField(choices=[('01', 'Artículos'), ('02', 'Reseñas'), ('03', 'Entrevistas'), ('04', 'En Profundidad'), ('05', 'Noticias')], default='01', max_length=60, verbose_name='Categoría')),
                ('donativo', models.CharField(choices=[('01', 'Publicar'), ('02', 'No Publicar')], default='01', max_length=60, verbose_name='Estado')),
                ('contenido', ckeditor.fields.RichTextField(max_length=180000, verbose_name='Sinopsis')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Entrada del Blog',
                'verbose_name_plural': 'Entradas del Blog',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='etiquetasBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Etiqueta')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cat_estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoriasEstudio', to='blog.CategoryStudyBlog', verbose_name='Categorias de estudio')),
                ('for_inline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.etiquetasBlog')),
            ],
            options={
                'verbose_name': 'Etiqueta Blog',
                'verbose_name_plural': 'Etiquetas Blog',
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='entradablog',
            name='etiquetaBlog',
            field=models.ManyToManyField(related_name='get_etiquetaCart', to='blog.etiquetasBlog', verbose_name='Etiquetas'),
        ),
    ]
