# Generated by Django 2.0.2 on 2019-05-21 21:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradablog',
            name='contenido',
            field=ckeditor.fields.RichTextField(max_length=180000, verbose_name='Contenido'),
        ),
    ]
