# Generated by Django 2.0.2 on 2019-03-17 03:12

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compañero',
                'verbose_name_plural': 'Compañeros del Foro',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='grupoForo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(max_length=200, null=True, verbose_name='Puesto')),
                ('info', ckeditor.fields.RichTextField(max_length=8000, verbose_name='Información')),
                ('imagenPerfil', models.ImageField(upload_to='nodos', verbose_name='Imagen de perfil')),
                ('imagenBanner', models.ImageField(upload_to='nodos', verbose_name='Imágen del Banner')),
                ('imagenExtra', models.ImageField(upload_to='nodos', verbose_name='Imágen extra')),
                ('linkface', models.URLField(blank=True, null=True, verbose_name='link')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.Colaborador', verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ['-created'],
            },
        ),
    ]
