# Generated by Django 2.0.2 on 2019-02-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historia',
            options={'ordering': ['created'], 'verbose_name': 'Línea del Tiempo', 'verbose_name_plural': 'Línea del Tiempo'},
        ),
        migrations.AlterField(
            model_name='historia',
            name='imagen',
            field=models.ImageField(upload_to='historia', verbose_name='portada del libro'),
        ),
    ]
