# Generated by Django 2.0.2 on 2019-02-28 01:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='faqs',
            fields=[
                ('id_faqs', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', ckeditor.fields.RichTextField(max_length=8000, verbose_name='Información')),
                ('respuesta', ckeditor.fields.RichTextField(max_length=8000, verbose_name='Información')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'faq',
                'verbose_name_plural': 'Faqs',
                'ordering': ['-created'],
            },
        ),
        migrations.DeleteModel(
            name='about',
        ),
    ]
