# Generated by Django 2.0.2 on 2019-02-28 01:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0002_auto_20190227_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqs',
            name='pregunta',
            field=ckeditor.fields.RichTextField(max_length=8000, verbose_name='Pregunta'),
        ),
        migrations.AlterField(
            model_name='faqs',
            name='respuesta',
            field=ckeditor.fields.RichTextField(max_length=8000, verbose_name='Respuesta'),
        ),
    ]
