# Generated by Django 2.0.2 on 2019-03-05 22:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('galeria', '0002_galeria_presentacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='galeria',
            new_name='imgGal',
        ),
    ]
