# Generated by Django 2.0.2 on 2019-03-03 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0003_auto_20190227_1947'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='faqs',
            new_name='preguntas',
        ),
    ]
