# Generated by Django 2.0.2 on 2019-03-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo', '0002_remove_repertorio_editorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repertorio',
            name='director',
            field=models.CharField(max_length=200, null=True, verbose_name='Director'),
        ),
    ]
