# Generated by Django 2.0.2 on 2019-04-22 02:59

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_estudio', models.CharField(max_length=200, verbose_name='Categoria de estudio')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria de etiqueta cartelera',
                'verbose_name_plural': 'Categorias de estudio etiquetas de cartelera',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='diaSemana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaSem', models.CharField(max_length=2, verbose_name='Día de la Semana')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Día de la Semana',
                'verbose_name_plural': 'Días de la Semana',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='etiquetasCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Etiqueta')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cat_estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoriasEstudio', to='cartelera.CategoryStudy', verbose_name='Categorias de estudio')),
                ('for_inline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cartelera.etiquetasCar')),
            ],
            options={
                'verbose_name': 'Etiqueta Cartelera',
                'verbose_name_plural': 'Etiqueta Cartelera',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='fechaCalendario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCa', models.CharField(max_length=2, verbose_name='Introduzca el/los días de función. ')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('for_inline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cartelera.fechaCalendario')),
            ],
            options={
                'verbose_name': 'Fecha de función',
                'verbose_name_plural': 'Fecha de funciones',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('autor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Autor')),
                ('director', models.CharField(blank=True, max_length=50, null=True, verbose_name='Director')),
                ('autorydir', models.CharField(blank=True, help_text='Si es Autor y Director dejar en blanco los espacios de la parte superior y solo llenar este.', max_length=50, null=True, verbose_name='Autor y Director')),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Presentaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentacion', models.CharField(choices=[('01', 'Programación Normal'), ('02', 'Presentación Especial')], default='01', help_text='Seleccione el tipo de presentación', max_length=60, verbose_name='Tipo de presentacion')),
                ('status', models.CharField(choices=[('01', 'En Temporada'), ('02', 'Fuera de Cartelera')], default='02', help_text='Seleccione si la obra aparece en Cartelera', max_length=60, verbose_name='Status de la obra')),
                ('Cartel', models.ImageField(upload_to='cartelera', verbose_name='Cartel de la Obra')),
                ('imagenPortada', models.ImageField(upload_to='cartelera', verbose_name='Foto de portada')),
                ('hora', models.CharField(default='21:00', help_text='Introduzca el horario de la presentación, ej: "21:00".', max_length=5, verbose_name='Hora')),
                ('donativo', models.CharField(choices=[('01', 'Donativo'), ('02', 'Precio')], default='01', max_length=60, verbose_name='Costo')),
                ('sinopsis', ckeditor.fields.RichTextField(max_length=8000, verbose_name='Sinopsis')),
                ('elenco', ckeditor.fields.RichTextField(max_length=8000, verbose_name='Reparto')),
                ('Agrupacion', models.CharField(default=None, max_length=100, verbose_name='Nombre de la Agrupación')),
                ('publico', models.CharField(choices=[('01', 'Público en general'), ('02', 'Adolecentes y adultos'), ('03', 'Función para niños')], default='01', max_length=60, verbose_name='Público')),
                ('duracion', models.CharField(default=None, help_text='Introduzca la duración de la presentación.', max_length=100, verbose_name='Duración')),
                ('grupoLink', models.URLField(blank=True, null=True, verbose_name='Link del Grupo')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('diaSem', models.ManyToManyField(help_text='Día(s) de la semana que se presenta la obra.', related_name='get_diaSem', to='cartelera.diaSemana', verbose_name='Día(s) de la semana. ')),
                ('etiquetasCartelera', models.ManyToManyField(help_text='Etiquetas para filtros', related_name='get_etiquetaCart', to='cartelera.etiquetasCar', verbose_name='Género y demás clasificaciones')),
                ('fechaCal', models.ManyToManyField(help_text='Seleccione los días que se presentará la obra.', related_name='get_fechaCal', to='cartelera.fechaCalendario', verbose_name='Días')),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartelera.Obra', verbose_name='Título')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Función',
                'verbose_name_plural': 'Funciones',
                'ordering': ['-created'],
            },
        ),
    ]
